doctrine_migrations:
    migrations_paths:
        # migrations classes should NOT be autoloaded
        'App\Migration': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: migr_migration
    enable_profiler: '%kernel.debug%'
