framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            async: '%env(resolve:MESSENGER_TRANSPORT_ASYNC_DSN)%'
            failed: '%env(resolve:MESSENGER_TRANSPORT_FAILED_DSN)%'

        routing:
            # Route your messages to the transports
            'Webmunkeez\CQRSBundle\Command\CommandInterface': sync
            'Webmunkeez\CQRSBundle\Query\QueryInterface': sync
            'Webmunkeez\CQRSBundle\Event\EventInterface': async
