stages:
    - build-images
    - test
    - deploy

variables:
    GATEWAY_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}/gateway

build-gateway-images:
    stage: build-images
    only:
        refs:
            - master
        changes:
            - docker/gateway/**/*
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker info
        - docker login ${CI_REGISTRY} --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD}
    after_script:
        - docker logout ${CI_REGISTRY}
    script:
        - docker build -t ${GATEWAY_REGISTRY_IMAGE}:latest -f ./docker/gateway/Dockerfile .
        - docker push ${GATEWAY_REGISTRY_IMAGE}:latest

test-gateway:
    stage: test
    only:
        - tags
    image: ${GATEWAY_REGISTRY_IMAGE}:latest
    script:
        - ls -al
        - APP_ENV=test composer install --no-interaction
        - yarn install
        - yarn dev
        - php-cs-fixer fix ./src --dry-run --diff
        - ./vendor/bin/phpunit

deploy-gateway:
    stage: deploy
    only:
        - tags
    image: ${GATEWAY_REGISTRY_IMAGE}:latest
    before_script:
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script:
        - APP_ENV=prod APP_DEBUG=0 composer install --no-dev --no-interaction --optimize-autoloader
        - APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
        - yarn install
        - yarn build
        - tar -cvzf ${CI_COMMIT_SHA}.tar.gz ./bin/console ./config ./migrations ./public ./src ./templates ./translations ./vendor
        - scp -p ${CI_COMMIT_SHA}.tar.gz ${SSH_USER}@${SSH_HOST}:${SSH_PATH}/releases
        - |
            ssh ${SSH_USER}@${SSH_HOST} /bin/bash -s << EOT
            cd ${SSH_PATH}
            mkdir -p releases/${CI_COMMIT_TAG}
            tar -xvzf releases/${CI_COMMIT_SHA}.tar.gz -C releases/${CI_COMMIT_TAG}/
            cp shared/.env.local.php releases/${CI_COMMIT_TAG}/.env.local.php
            rm releases/${CI_COMMIT_SHA}.tar.gz
            ln -sfn releases/${CI_COMMIT_TAG} current
            EOT
