version: '3.9'

services:
  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - gateway-symfony
    volumes:
      - ./apps/gateway/app:/www/gateway:delegated
      - ./apps/file-manager:/www/file-manager:delegated
      - ./docker/nginx/log:/var/log/nginx:delegated
    ports:
      - 3000:3000
      - 3001:3001

  gateway-symfony:
    build:
      context: ./docker/symfony
    depends_on:
      - gateway-postgres
    volumes:
      - ./apps/gateway/app:/www/gateway:delegated
      - ./apps/file-manager:/www/file-manager:delegated

  gateway-postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_password
      POSTGRES_DB: gateway_db
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
