version: '3.9'

services:
  gateway:
    build:
      context: ./docker/gateway
    depends_on:
      - database
    volumes:
      - .:/www:delegated
    ports:
      - 8000:8000

  database:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
