services:
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Fixture\:
        resource: '../fixtures'
        autowire: true
        autoconfigure: true